[tool.briefcase]
project_name = "1-2-3 sound effects"
bundle = "com.example"
version = "0.0.1"
url = "https://coolcoder613.glitch.me/download"
license = "MIT license"
author = 'coolcoder613'
author_email = "coolcoder613@outlook.com"

[tool.briefcase.app.onetwothreesoundeffects]
formal_name = "1-2-3 sound effects"
description = "an application with sound effects"
icon = "src/onetwothreesoundeffects/resources/onetwothreesoundeffects"
sources = ['src/onetwothreesoundeffects']
requires = ['toga'
]


[tool.briefcase.app.onetwothreesoundeffects.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.onetwothreesoundeffects.linux]
requires = [
    'toga-gtk>=0.3.0.dev34',
]

[tool.briefcase.app.onetwothreesoundeffects.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.onetwothreesoundeffects.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.onetwothreesoundeffects.windows]
requires = [
    'toga-winforms>=0.3.0.dev34','toga>=0.3.0.dev34'
]

# Mobile deployments
[tool.briefcase.app.onetwothreesoundeffects.iOS]
requires = [
    'toga-iOS>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.onetwothreesoundeffects.android]
requires = [
    'toga-android>=0.3.0.dev34'
]
